language: java

jdk: oraclejdk8

branches:
  only:
  - master

install:
  - chmod +x ./gradlew

script:
  - ./gradlew wrapper clean compileJava
  - ./gradlew check

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: change
    on_failure: always
